sudo: required

services:
  - docker

before_install: 
  - docker build -t matheustessaro/docker-react -f Dockerfile.dev .

script:
  - docker run matheustessaro/docker-react npm run test -- --coverage