FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# copy contents from local folder (frontend) to /app
COPY . .

# -v = docker volumes
# pwd = present working directory (it's a command)

CMD [ "npm", "run", "start" ]